import React from 'react';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Image from 'next/image';
import Link from 'next/link';
import { Providers } from './providers';
import { FaGithub } from 'react-icons/fa';
import { FaBolt, FaBug, FaLightbulb, FaSun, FaYoutube } from 'react-icons/fa6';

const inter = Inter({ subsets: ['latin'] });

export type AppEnvConfig = {
  apiHostname: string | undefined;
  apiContextPath: string | undefined;
};
export function getAppEnvConfig(): { apiContextPath: any; apiHostname: any } {
  return {
    apiHostname: process.env.NEXT_PUBLIC_BACKEND_API_HOST,
    apiContextPath: process.env.NEXT_PUBLIC_BACKEND_API_CONTEXT_PATH,
  };
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const envConfig = getAppEnvConfig();

  return (
    <html lang='en'>
      <head>
        <title>
          How Often App - Observational Health Data Sciences and Informatics
        </title>
      </head>
      <body className='p-12'>
        <Providers>
          <header className='mx-auto flex max-w-screen-xl'>
            <div className='flex-1 pl-4'>
              <Link href='\'>
                <Image
                  src='/ohdsi-logo-with-text.png'
                  width='200'
                  height='51'
                  alt='The Observational Health Data Sciences and Informatics Logo'
                />
              </Link>
            </div>
            <div className='m-auto pr-4 align-middle'>
              <Link href='https://stackblitz.com/fork/github/ecruz165/drug-condition-incidence/tree/feature/migrate-datasource-to-postgres-as-part-of-app-deployment/frontend-modern'>
                <FaBolt size={25} aria-label='Open frontend in Stackblitz' />
              </Link>
            </div>
            <div className='m-auto pr-4 align-middle'>
              <Link
                href='https://github.com/cumc-dbmi/drug-condition-incidence'
                target={'_github'}
              >
                <FaGithub size={25} aria-label='Fork this project' />
              </Link>
            </div>
            <div className='m-auto pr-4 align-middle'>
              <Link
                href='https://github.com/cumc-dbmi/drug-condition-incidence/issues/new?labels=bug'
                target={'_github'}
              >
                <FaBug size={25} aria-label='Report a bug' />
              </Link>
            </div>
            <div className='m-auto pr-4 align-middle'>
              <Link href='https://www.youtube.com/watch?v=VQMsB_t0c2E'>
                <FaYoutube
                  size={25}
                  aria-label='Learn about the How Often initiative'
                />
              </Link>
            </div>
            <div className='m-auto pr-4 align-middle'>
              <Link href='#'>
                <FaSun size={25} aria-label='Switch to dark mode' />
              </Link>
            </div>
          </header>

          {children}
        </Providers>
      </body>
    </html>
  );
}
